---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MongoDB
  apt:
    name: mongodb-org
    state: present
    update_cache: yes

- name: Create data directory
  file:
    path: /data/db
    state: directory
    owner: mongodb
    group: mongodb
    mode: '0755'

- name: Copy mongod.conf template
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart MongoDB

- name: Start and enable MongoDB service
  service:
    name: mongod
    state: started
    enabled: yes

- name: Wait for MongoDB to be ready
  wait_for:
    host: localhost
    port: "{{ mongodb_port }}"
    timeout: 30

- name: Set MongoDB master and replica IPs
  set_fact:
    mongodb_master_ip: "{{ hostvars[groups['infra-server'][0]].private_ip_address }}"
    mongodb_replica_ip: "{{ hostvars[groups['infra-server'][1]].private_ip_address }}"

- name: Create replica set initiation script
  template:
    src: rs_init.js.j2
    dest: /tmp/rs_init.js

- name: Initiate MongoDB replica set
  shell: |
    mongo --quiet --host {{ mongodb_master_ip }} < /tmp/rs_init.js || echo "Replica set may already be configured"
  delegate_to: "{{ mongodb_master_ip }}"
  run_once: true
