---
- name: Import MongoDB public GPG key
  apt_key:
    url: https://pgp.mongodb.com/server-6.0.asc
    state: present

- name: Add MongoDB repository
  apt_repository:
    repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release | lower }}/mongodb-org/6.0 multiverse"
    state: present
    filename: "mongodb-org-6.0"

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install MongoDB
  apt:
    name: mongodb-org
    state: present

- name: Create data directory
  file:
    path: /data/db
    state: directory
    owner: mongodb
    group: mongodb
    mode: '0755'

- name: Copy mongod.conf template
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart MongoDB

- name: Start and enable MongoDB service
  service:
    name: mongod
    state: started
    enabled: yes

- name: Wait for MongoDB to be ready
  wait_for:
    host: localhost
    port: "{{ mongodb_port }}"
    timeout: 30
